version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: dellbeer-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: dellbeer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
